version: '3.8'

# Application Services
services:

  # http app proxy ?
  laravel-php:
    container_name: deets_laravel_php_v2
    #build:
    image: ghcr.io/deets-pro/php_laravel_deets:latest
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
    networks: 
      - laravel_v2
    env_file:
      - stack.env

  webserver:
    container_name: deets_nginx_webserver_v2
    image: "ghcr.io/deets-pro/nginx_webserver_image:latest"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
    depends_on:
      - laravel-php
    networks:
      - laravel_v2
    env_file:
      - stack.env

  pyhasher:
    container_name: deets_py_hasher_v2
    image: "ghcr.io/deets-pro/py_dockerized_scrypt_hasher_service:latest"
    ports:
      - "${PYHASHER_PORT}:5959"
    networks:
      - laravel_v2
    env_file:
      - stack.env

#Docker Networks
networks:
  laravel_v2:
    driver: bridge

#Volumes
volumes:
  persistent: {}