version: '3.8'

# Application Services
services:

  # http app proxy ?
  deets-app:
    container_name: deets_laravel_php_v2
    #build:
    image: "ghcr.io/deets-pro/php_laravel_deets:latest"
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
    networks: 
      - deets-network
    env_file:
      - stack.env

  webserver:
    container_name: deets_nginx_webserver_v2
    image: "ghcr.io/deets-pro/docker_nginx_webserver_image:latest"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - deets-app
    networks:
      - deets-network
    env_file:
      - stack.env

  pyhasher:
    container_name: deets_py_hasher_v2
    image: "ghcr.io/deets-pro/docker_py_scrypt_hasher:latest"
    ports:
      - "${PYHASHER_PORT}:5959"
    networks:
      - laravel_v2
    env_file:
      - stack.env

#Docker Networks
networks:
  deets-network:
    driver: bridge

#Volumes
volumes:
  persistent: {}