version: '3.8'

# Application Services
services:
  app:
    container_name: deets_laravel_php
    image: ghcr.io/deets-pro/php_laravel_deets:latest
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
    networks: 
      - deets_network
    pull_policy: always
    restart: unless-stopped
    env_file:
      - stack.env

  webserver:
    container_name: deets_nginx_webserver
    image: "ghcr.io/deets-pro/docker_nginx_webserver_image:latest"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - persistent:/var/www/html/:delegated
      - /home/deets/storage/:/var/www/html/storage/:delegated
    depends_on:
      - app
    networks:
      - deets_network
    pull_policy: always
    restart: unless-stopped
    env_file:
      - stack.env

  pyhasher:
    container_name: deets_py_hasher
    image: "ghcr.io/deets-pro/docker_py_scrypt_hasher:latest"
    ports:
      - "${PYHASHER_PORT}:5959"
    networks:
      - deets_network
    pull_policy: always
    restart: unless-stopped
    env_file:
      - stack.env

  pass_generator:
    container_name: wallet_pass-api-2
    image: "ghcr.io/deets-pro/js_express_walletpass_generator_service:latest"
    networks:
      - deets_network
    pull_policy: always
    restart: unless-stopped
    env_file:
      - stack.env

#Docker Networks
networks:
  deets_network:
    driver: bridge

#Volumes
volumes:
  persistent: {}